name: Upload Release

description: Uploads a built release file to Azure Blob Storage

inputs:
  artifact_name:
    description: artifact name

    required: true

  upload_to_azure:
    description: upload to Azure Blob Storage

    required: true

  azure_storage_account_name:
    description: Azure storage account name

    required: true

  azure_storage_account_key:
    description: Azure storage account key

    required: true

  container_name:
    description: Azure Blob Storage container name

    required: true

  source:
    description: source location

    required: false

    default: ""

runs:
  using: "composite"

  steps:
    - name: Save artifact

      uses: actions/upload-artifact@v4

      with:
        name: ${{ inputs.artifact_name }}

        path: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}/${{ inputs.artifact_name }}

    - name: Install Azure CLI
      if: inputs.upload_to_azure == 'true'
      run: |

        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      shell: bash

    - name: Upload build to Azure Blob Storage
      if: github.event_name == 'push' && inputs.upload_to_azure == 'true'
      working-directory: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}
      env:
        ARTIFACT_NAME: ${{ inputs.artifact_name }}
        AZURE_ACCOUNT_NAME: ${{ inputs.azure_storage_account_name }}
        AZURE_ACCOUNT_KEY: ${{ inputs.azure_storage_account_key }}
        CONTAINER_NAME: ${{ inputs.container_name }}
      run: |
        FILE_PATH="${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}/${ARTIFACT_NAME}"
        if [ -f "$FILE_PATH" ]; then
          echo "Starting upload of ${ARTIFACT_NAME} to Azure Blob Storage..."
          az storage blob upload \
            --account-name $AZURE_ACCOUNT_NAME \
            --account-key $AZURE_ACCOUNT_KEY \
            --container-name $CONTAINER_NAME \
            --name $ARTIFACT_NAME \
            --file "$FILE_PATH"
          echo "Upload completed for ${ARTIFACT_NAME}."
          echo "Debug Information:"
          echo "Artifact Name: $ARTIFACT_NAME"
          echo "Container Name: $CONTAINER_NAME"
          echo "File Path: $FILE_PATH"
          echo "File Size: $(stat -c %s "$FILE_PATH") bytes"
        else
          echo "File $FILE_PATH does not exist."
          exit 1
        fi
      shell: bash

    - name: Create Continuous Release
      if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' && inputs.github_token != '' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        target_commitish: master
        files: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}/${{ inputs.artifact_name }}
        name: "Continuous Release"
        body: "This release is continuously updated with every commit to master."
        draft: false
        prerelease: true
        token: ${{ inputs.github_token }}
